spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/evsms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
server:
  error:
    include-message: always
